# Generated by Django 3.0.8 on 2020-07-25 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20200724_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentheader',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.Activity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.Activity'),
            preserve_default=False,
        ),
    ]
