# Generated by Django 3.0.8 on 2020-07-25 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20200725_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='activity',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='content_header',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.ContentHeader'),
            preserve_default=False,
        ),
    ]
