# Generated by Django 3.0.8 on 2020-07-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20200725_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
