# Generated by Django 3.0.8 on 2020-07-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_auto_20200726_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Activity'),
        ),
    ]
